# Generated by Django 4.2.16 on 2025-11-12 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepayment',
            name='loan_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_repayments', to='dashboard.loanapplication'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_update', 'Application Update'), ('payment_reminder', 'Payment Reminder'), ('system', 'System Notification'), ('withdrawal', 'Withdrawal Update'), ('payment', 'Payment Update')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoanWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('withdrawal_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.loanapplication')),
            ],
            options={
                'ordering': ['-withdrawal_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash Deposit')], default='mpesa', max_length=20)),
                ('mpesa_number', models.CharField(blank=True, max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('is_installment', models.BooleanField(default=True)),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('loan_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.loanapplication')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
