# Generated by Django 4.2.16 on 2025-11-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_loanrepayment_loan_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandocument',
            name='document_type',
            field=models.CharField(choices=[('id_front', 'National ID Front'), ('id_back', 'National ID Back'), ('passport', 'Passport Photo'), ('payslip', 'Payslip'), ('bank_statement', 'Bank Statement'), ('business_registration', 'Business Registration'), ('other', 'Other')], max_length=50),
        ),
    ]
