# Generated by Django 4.2.16 on 2025-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_loandocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanpayment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('cash', 'Cash Deposit')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LoanRepayment',
        ),
    ]
