# Generated by Django 4.2.16 on 2025-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_loanpayment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.png', null=True, upload_to='profile_pictures/%Y/%m/%d/'),
        ),
    ]
